version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  s3: circleci/aws-s3@3.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build_backend:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - run: 
          name: 'Install Dependencies'
          command: "cd udagram-api && npm install --save"
      - run:
          name: "Build API"
          command: "cd udagram-api && npm run build"
      - persist_to_workspace:
          root: .
          paths:
            - 'www'
  build_frontend:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - run: 
          name: 'Install Dependencies'
          command: "cd udagram-frontend && npm install --save"
      - run:
          name: "Build Frontend"
          command: |
            cd udagram-frontend
            npm run build
  deploy_backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: .
      - run: "ls"
    
workflows:
  build_deploy:
    jobs:
      - build_frontend
      - build_backend
      - deploy_backend:
          requires:
            - build_backend