version: 2.1

orbs: # Orbs used in the pipeline
  node: circleci/node@4.1.0 # For npm install, build scripts etc..
  aws-cli: circleci/aws-cli@2.0.3 # Configures AWS to be used by both S3 and EB
  s3: circleci/aws-s3@3.0.0 # To deploy frontend to S3 Bucket
  eb: circleci/aws-elastic-beanstalk@2.0.1 # To deploy backend to EB

jobs:
  build_backend:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout 
      - restore_cache: # restore cached node_modules
          keys:
            - node_modules-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node_modules-api-{{ .Branch }}-
            - node_modules-api-
      - run:
          name: 'Install Dependencies'
          command: "cd udagram-api && npm install --save"
      - save_cache: # cache node_modules
          paths:
            - udagram-api/node_modules 
          key: node_modules-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: # Build the project
          name: "Build API"
          command: "cd udagram-api && npm run build"
      - persist_to_workspace: # keeping the www directory for the next job (deployment) 
          root: .
          paths:
            - 'udagram-api/www'
  build_frontend:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - restore_cache: # restore cached node_modules
          keys:
            - node_modules-front-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node_modules-front-{{ .Branch }}-
            - node_modules-front-
      - run: 
          name: 'Install Dependencies'
          command: "cd udagram-frontend && npm install --save"
      - save_cache: # cache node_modules
          paths:
            - udagram-frontend/node_modules 
          key: node_modules-front-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: # Build the project
          name: "Build Frontend"
          command: |
            cd udagram-frontend
            npx ng build --prod
      - persist_to_workspace: # keeping the www directory for the next job (deployment) 
          root: .
          paths:
            - 'udagram-frontend/www'
  deploy_frontend:
    docker:
      - image: "cimg/base:stable"
    parameters:
      bucket: # Taking a bucket name parameter
        type: string
        default: ""
    steps:
      - aws-cli/setup # Configure AWS
      - attach_workspace: # Retreive the persisting www folder
          at: .
      - s3/sync: # Upload new changes to S3 bucket
          arguments: "--acl public-read"
          from: "udagram-frontend/www"
          to: <<parameters.bucket>>
  deploy_backend:
    docker:
      - image: "cimg/python:3.7"
    parameters:
      app-name: # EB app name parameter
        type: string
        default: ""
      env-name: # EB env name parameter
        type: string
        default: ""
      region-name: # AWS region parameter
        type: string
        default: ""
    steps:
      - attach_workspace: # Retreive the persisting www folder
          at: .
      - aws-cli/setup # Configure AWS
      - eb/setup # EB CLI setup
      - run: # Deploy to EB. --profile default argument to use AWS Credentials
          name: "Elastic beanstalk Deploy"
          command: |
            eb init <<parameters.app-name>> --region <<parameters.region-name>> --platform node.js --profile default
            eb deploy <<parameters.env-name>>
            eb status
          working_directory: "udagram-api/www"
          
workflows:
  frontend:
    jobs:
      - build_frontend
      - deploy_frontend:
          bucket: "s3://9951-udagram/" # S3 bucket
          requires: 
            - build_frontend # Waits for build job to complete
  backend:
    jobs:
      - build_backend
      - deploy_backend:
          requires:
            - build_backend # Waits for build job to complete
          app-name: "udagram-api" # EB app
          env-name: "udagram-api-dev" # EB app env
          region-name: "eu-central-1" # AWS region
