version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  s3: circleci/aws-s3@3.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  setup_node:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      #- aws-cli/setup
      #- eb/setup
      - run: "ls"
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - run: "ls"
    
  build_backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: "ls"
      - attach_workspace:
            at: .
      - run: "ls"
      - run: 
          name: 'Install Dependencies'
          command: "cd udagram-api && npm install --save"
      - run:
          name: "Build API"
          command: "cd udagram-api && npm run build"
      - run: "ls"
      - persist_to_workspace:
          root: .
          paths:
            - 'www'
      - run: "ls"
  build_frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: "ls"
      - attach_workspace:
            at: .
      - run: "ls"
      - run: 
          name: 'Install Dependencies'
          command: "cd udagram-frontend && npm install --save"
      - run:
          name: "Build Frontend"
          command: |
            cd udagram-frontend
            npm run build
      - run: "ls"

workflows:
  build_deploy:
    jobs:
      - setup_node
      - build_frontend:
          requires:
            - setup_node
      - build_backend:
          requires:
            - setup_node